#
# Copyright 2021 zero323
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from delta.tables import (
    DeltaTable as DeltaTable,
    DeltaTableBuilder as DeltaTableBuilder,
)
from delta.testing.utils import DeltaTestCase as DeltaTestCase

class DeltaTableTests(DeltaTestCase):
    def test_forPath(self) -> None: ...
    def test_forName(self) -> None: ...
    def test_alias_and_toDF(self) -> None: ...
    def test_delete(self) -> None: ...
    def test_generate(self) -> None: ...
    def test_update(self) -> None: ...
    def test_merge(self) -> None: ...
    def test_history(self) -> None: ...
    def test_vacuum(self) -> None: ...
    def test_convertToDelta(self) -> None: ...
    def test_isDeltaTable(self) -> None: ...
    def test_create_table_with_existing_schema(self) -> None: ...
    def test_create_replace_table_with_no_spark_session_passed(self) -> None: ...
    def test_create_table_with_name_only(self) -> None: ...
    def test_create_table_with_location_only(self) -> None: ...
    def test_create_table_with_name_and_location(self) -> None: ...
    def test_create_table_behavior(self) -> None: ...
    def test_replace_table_with_name_only(self) -> None: ...
    def test_replace_table_with_location_only(self) -> None: ...
    def test_replace_table_with_name_and_location(self) -> None: ...
    def test_replace_table_behavior(self) -> None: ...
    def test_verify_paritionedBy_compatibility(self) -> None: ...
    def test_delta_table_builder_with_bad_args(self) -> None: ...
    def test_protocolUpgrade(self) -> None: ...
